# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Import Signing Key
      run: |
        cat << EOF > ./key.gpg
        ${{ secrets.GPG_KEY }}
        EOF
        gpg --import --batch ./key.gpg
        gpg --pinentry-mode loopback --passphrase ${{ secrets.GPG_PASSWORD}} --export-secret-keys A47EDDB49D1CC789 > /home/runner/.gnupg/secring.gpg
    - name: Generate Gradle Properties
      run: |
        cat << EOF > ./gradle.properties
        artifactory_user=github
        artifactory_password=${{ secrets.ARTIFACTORY_PASSWORD }}
        artifactory_contextUrl=https://adzerkps.jfrog.io/artifactory
        nexusUsername=test
        nexusPassword=placeholder
        signing.keyId=9D1CC789
        signing.password=${{ secrets.GPG_PASSWORD }}
        signing.secretKeyRingFile=/home/runner/.gnupg/secring.gpg
        EOF
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload gradle.properties
      uses: actions/upload-artifact@v1
      with:
        name: properties
        path: gradle.properties
    - name: Upload Build
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download gradle.properties
      uses: actions/download-artifact@v1
      with:
        name: properties
        path: ./
    - name: Download Build
      uses: actions/download-artifact@v1
      with:
        name: build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download gradle.properties
      uses: actions/download-artifact@v1
      with:
        name: properties
        path: ./
    - name: Download Build
      uses: actions/download-artifact@v1
      with:
        name: build
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Update Version
      run: sed -i -r "s/^version = '[0-9a-z.-]+'\$/version = '${GITHUB_REF##*/}'/g" build.gradle
    - name: Publish with Gradle
      run: ./gradlew artifactoryPublish